#! /usr/bin/env bash
set -e
this_dir="$(readlink -f "$(dirname "$0")")"


if [[ -n $XDG_DATA_HOME && ! -e $XDG_DATA_HOME/decaf-emu ]]; then
	mkdir $XDG_DATA_HOME/decaf-emu
	export SHAREPATH=$XDG_DATA_HOME/decaf-emu
elif	[[ ! -e $HOME/.local/share/decaf-emu ]]; then
	mkdir $HOME/.local/share/decaf-emu
	export SHAREPATH=$HOME/.local/share/decaf-emu
fi
if [[ -n $XDG_CONFIG_HOME && ! -e $XDG_CONFIG_HOME/decaf ]]; then
	mkdir $XDG_CONFIG_HOME/decaf
	export CONFIGPATH=$XDG_CONFIG_HOME/decaf
	if [[ ! -e "$CONFIGPATH"/config.toml ]]; then
		sed -e "s|<SHAREPATH>|$SHAREPATH|g" "$APPDIR"/usr/resources/config.toml.app > "$CONFIGPATH"/config.toml
	fi
elif	[[ ! -e $HOME/.config/decaf ]]; then
	mkdir $HOME/.config/decaf
	export CONFIGPATH=$HOME/.config/decaf
	if [[ ! -e "$CONFIGPATH"/config.toml ]]; then
		sed -e "s|<SHAREPATH>|$SHAREPATH|g" "$APPDIR"/usr/resources/config.toml.app > "$CONFIGPATH"/config.toml
	fi
fi

exec "$this_dir"/AppRun.wrapped "$@"
