name: C/C++ CI

on: 
  push:
    branches: 
      #- main

jobs:
  build:
    name: ubuntu-20.04-gcc-10
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
    - name: Checkout Upstream Repo
      uses: actions/checkout@v3
      with:
        repository: decaf-emu/decaf-emu
        ref: master

    - name: Checkout AppImage Repo
      uses: actions/checkout@v3
      with:
          clean: false
          path: appimage

    - name: cache
      uses: actions/cache@v2
      with:
        path: ~/.ccache
        key: build-ccache-${{github.run_id}}
        restore-keys: |
          build-ccache
          
    - name: Initialise
      run: mkdir build

    - name: Install Dependencies 
      run: |
          chmod +x appimage/.github/workflows/install-script.sh
          appimage/.github/workflows/install-script.sh

    - name: Configure (Ubuntu)
      run: |
        cd build
        cmake -GNinja -DCMAKE_C_COMPILER=/usr/lib/ccache/gcc -DCMAKE_CXX_COMPILER=/usr/lib/ccache/g++ -DDECAF_BUILD_TOOLS=ON -DDECAF_FFMPEG=ON -DDECAF_VULKAN=ON -DDECAF_QT=ON -DCMAKE_BUILD_TYPE=Release -DQt5_DIR=$QTDIR/lib/cmake/Qt5 -DCMAKE_INSTALL_PREFIX=install ..

    - name: Build
      run: |
        cd build
        cmake --build . --config Release -j 2 --target install

    - name: Package AppImage
      run: |
        chmod +x appimage/.github/workflows/appimage.sh
        appimage/.github/workflows/appimage.sh
        mv build/install build/install2
        mv artifacts build/install
        
    - uses: actions/upload-artifact@master
      with:
        name: decaf-emu-ubuntu
        path: build/install
